<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\SicDetails;

class TwoColumnSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['code_id' => '56302', 'code_name' => 'Public houses and bars'],
            ['code_id' => '56301', 'code_name' => 'Licenced clubs'],
            ['code_id' => '563290', 'code_name' => 'Other food services'],
            ['code_id' => '56210', 'code_name' => 'Event catering activities'],
            ['code_id' => '56103', 'code_name' => 'Take-away food shops and mobile food stands'],
            ['code_id' => '56102', 'code_name' => 'Unlicenced restaurants and cafes'],
            ['code_id' => '56101', 'code_name' => 'Licenced restaurants'],
            ['code_id' => '55900', 'code_name' => 'Other accommodation'],
            ['code_id' => '55300', 'code_name' => 'Recreational vehicle parks, trailer parks and camping grounds'],
            ['code_id' => '55209', 'code_name' => 'Other holiday and other collective accommodation'],
            ['code_id' => '55202', 'code_name' => 'Youth hostels'],
            ['code_id' => '55201', 'code_name' => 'Holiday centres and villages'],
            ['code_id' => '55100', 'code_name' => 'Hotels and similar accommodation'],
            ['code_id' => '99999', 'code_name' => 'Dormant Company'],
            ['code_id' => '99000', 'code_name' => 'Activities of extraterritorial organisations and bodies'],
            ['code_id' => '98200', 'code_name' => 'Undifferentiated service-producing activities of private households for own use'],
            ['code_id' => '98100', 'code_name' => 'Undifferentiated goods-producing activities of private households for own use'],
            ['code_id' => '98000', 'code_name' => 'Residents property management'],
            ['code_id' => '97000', 'code_name' => 'Activities of households as employers of domestic personnel'],
            ['code_id' => '82990', 'code_name' => 'Other business support service activities n.e.c.'],
            ['code_id' => '82920', 'code_name' => 'Packaging activities'],
            ['code_id' => '82912', 'code_name' => 'Activities of credit bureaus'],
            ['code_id' => '82911', 'code_name' => 'Activities of collection agencies'],
            ['code_id' => '82302', 'code_name' => 'Activities of conference organisers'],
            ['code_id' => '82301', 'code_name' => 'Activities of exhibition and fair organisers'],
            ['code_id' => '82200', 'code_name' => 'Activities of call centres'],
            ['code_id' => '82190', 'code_name' => 'Photocopying, document preparation and other specialised office support activities'],
            ['code_id' => '82110', 'code_name' => 'Combined office administrative service activities'],
            ['code_id' => '81300', 'code_name' => 'Landscape service activities'],
            ['code_id' => '81299', 'code_name' => 'Other cleaning services'],
            ['code_id' => '81291', 'code_name' => 'Disinfecting and exterminating services'],
            ['code_id' => '81229', 'code_name' => 'Other building and industrial cleaning activities'],
            ['code_id' => '81223', 'code_name' => 'Furnace and chimney cleaning services'],
            ['code_id' => '81222', 'code_name' => 'Specialised cleaning services'],
            ['code_id' => '81221', 'code_name' => 'Window cleaning services'],
            ['code_id' => '81210', 'code_name' => 'General cleaning of buildings'],
            ['code_id' => '81100', 'code_name' => 'Combined facilities support activities'],
            ['code_id' => '80300', 'code_name' => 'Investigation activities'],
            ['code_id' => '80200', 'code_name' => 'Security systems service activities'],
            ['code_id' => '80100', 'code_name' => 'Private security activities'],
            ['code_id' => '79909', 'code_name' => 'Other reservation service activities n.e.c.'],
            ['code_id' => '79901', 'code_name' => 'Activities of tourist guides'],
            ['code_id' => '79120', 'code_name' => 'Tour operator activities'],
            ['code_id' => '79110', 'code_name' => 'Travel agency activities'],
            ['code_id' => '78300', 'code_name' => 'Human resources provision and management of human resources functions'],
            ['code_id' => '78200', 'code_name' => 'Temporary employment agency activities'],
            ['code_id' => '78109', 'code_name' => 'Other activities of employment placement agencies'],
            ['code_id' => '78101', 'code_name' => 'Motion picture, television and other theatrical casting activities'],
            ['code_id' => '77400', 'code_name' => 'Leasing of intellectual property and similar products, except copyright works'],
            ['code_id' => '77390', 'code_name' => 'Renting and leasing of other machinery, equipment and tangible goods n.e.c.'],
            ['code_id' => '77352', 'code_name' => 'Renting and leasing of freight air transport equipment'],
            ['code_id' => '77351', 'code_name' => 'Renting and leasing of air passenger transport equipment'],
            ['code_id' => '77342', 'code_name' => 'Renting and leasing of freight water transport equipment'],
            ['code_id' => '77341', 'code_name' => 'Renting and leasing of passenger water transport equipment'],
            ['code_id' => '77330', 'code_name' => 'Renting and leasing of office machinery and equipment (including computers)'],
            ['code_id' => '77320', 'code_name' => 'Renting and leasing of construction and civil engineering machinery and equipment'],
            ['code_id' => '77310', 'code_name' => 'Renting and leasing of agricultural machinery and equipment'],
            ['code_id' => '77299', 'code_name' => 'Renting and leasing of other personal and household goods'],
            ['code_id' => '77291', 'code_name' => 'Renting and leasing of media entertainment equipment'],
            ['code_id' => '77220', 'code_name' => 'Renting of video tapes and disks'],
            ['code_id' => '77210', 'code_name' => 'Renting and leasing of recreational and sports goods'],
            ['code_id' => '77120', 'code_name' => 'Renting and leasing of trucks and other heavy vehicles'],
            ['code_id' => '77110', 'code_name' => 'Renting and leasing of cars and light motor vehicles'],
            ['code_id' => '01250', 'code_name' => 'Growing of other tree and bush fruits and nuts'],
            ['code_id' => '03220', 'code_name' => 'Freshwater aquaculture'],
            ['code_id' => '03210', 'code_name' => 'Marine aquaculture'],
            ['code_id' => '03120', 'code_name' => 'Freshwater fishing'],
            ['code_id' => '03110', 'code_name' => 'Marine fishing'],
            ['code_id' => '02400', 'code_name' => 'Support services to forestry'],
            ['code_id' => '02300', 'code_name' => 'Gathering of wild growing non-wood products'],
            ['code_id' => '02200', 'code_name' => 'Logging'],
            ['code_id' => '02100', 'code_name' => 'Silviculture and other forestry activities'],
            ['code_id' => '01700', 'code_name' => 'Hunting, trapping and related service activities'],
            ['code_id' => '01640', 'code_name' => 'Freshwater fishingSeed processing for propagation'],
            ['code_id' => '01630', 'code_name' => 'Post-harvest crop activities'],
            ['code_id' => '01629', 'code_name' => 'Support activities for animal production (other than farm animal boarding and care) n.e.c.'],
            ['code_id' => '01621', 'code_name' => 'Farm animal boarding and care'],
            ['code_id' => '01610', 'code_name' => 'Support activities for crop production'],
            ['code_id' => '01500', 'code_name' => 'Mixed farming'],
            ['code_id' => '01490', 'code_name' => 'Raising of other animals'],
            ['code_id' => '01470', 'code_name' => 'Raising of poultry'],
            ['code_id' => '01460', 'code_name' => 'Raising of swine / pigs'],
            ['code_id' => '01450', 'code_name' => 'Raising of sheep and goats'],
            ['code_id' => '01440', 'code_name' => 'Raising of camels and camelids'],
            ['code_id' => '01430', 'code_name' => 'Raising of horses and other equines'],
            ['code_id' => '01420', 'code_name' => 'Raising of other cattle and buffaloes'],
            ['code_id' => '01410', 'code_name' => 'Raising of dairy cattle'],
            ['code_id' => '01300', 'code_name' => 'Plant propagation'],
            ['code_id' => '01290', 'code_name' => 'Growing of other perennial crops'],
            ['code_id' => '01280', 'code_name' => 'Growing of spices, aromatic, drug and pharmaceutical crops'],
            ['code_id' => '01270', 'code_name' => 'Growing of beverage crops'],
            ['code_id' => '01260', 'code_name' => 'Growing of oleaginous fruits'],
            ['code_id' => '01240', 'code_name' => 'Growing of pome fruits and stone fruits'],
            ['code_id' => '01230', 'code_name' => 'Growing of citrus fruits'],
            ['code_id' => '01220', 'code_name' => 'Growing of tropical and subtropical fruits'],
            ['code_id' => '01210', 'code_name' => 'Growing of grapes'],
            ['code_id' => '01190', 'code_name' => 'Growing of other non-perennial crops'],
            ['code_id' => '01160', 'code_name' => 'Growing of fibre crops'],
            ['code_id' => '01150', 'code_name' => 'Growing of tobacco'],
            ['code_id' => '01140', 'code_name' => 'Growing of sugar cane'],
            ['code_id' => '01130', 'code_name' => 'Growing of vegetables and melons, roots and tubers'],
            ['code_id' => '01120', 'code_name' => 'Growing of rice'],
            ['code_id' => '01110', 'code_name' => 'Growing of cereals (except rice), leguminous crops and oil seeds'],
            ['code_id' => '93290', 'code_name' => 'Other amusement and recreation activities n.e.c.'],
            ['code_id' => '93210', 'code_name' => 'Activities of amusement parks and theme parks'],
            ['code_id' => '93199', 'code_name' => 'Other sports activities'],
            ['code_id' => '93191', 'code_name' => 'Activities of racehorse owners'],
            ['code_id' => '93130', 'code_name' => 'Fitness facilities'],
            ['code_id' => '93120', 'code_name' => 'Activities of sport clubs'],
            ['code_id' => '93110', 'code_name' => 'Operation of sports facilities'],
            ['code_id' => '92000', 'code_name' => 'Gambling and betting activities'],
            ['code_id' => '91040', 'code_name' => 'Botanical and zoological gardens and nature reserves activities'],
            ['code_id' => '91030', 'code_name' => 'Operation of historical sites and buildings and similar visitor attractions'],
            ['code_id' => '91020', 'code_name' => 'Museums activities'],
            ['code_id' => '91012', 'code_name' => 'Archives activities'],
            ['code_id' => '91011', 'code_name' => 'Library activities'],
            ['code_id' => '90040', 'code_name' => 'Operation of arts facilities'],
            ['code_id' => '90030', 'code_name' => 'Artistic creation'],
            ['code_id' => '90020', 'code_name' => 'Support activities to performing arts'],
            ['code_id' => '90010', 'code_name' => 'Performing arts'],
            ['code_id' => '43999', 'code_name' => 'Other specialised construction activities n.e.c.'],
            ['code_id' => '43991', 'code_name' => 'Scaffold erection'],
            ['code_id' => '43910', 'code_name' => 'Roofing activities'],
            ['code_id' => '43390', 'code_name' => 'Other building completion and finishing'],
            ['code_id' => '43342', 'code_name' => 'Glazing'],
            ['code_id' => '43341', 'code_name' => 'Painting'],
            ['code_id' => '43330', 'code_name' => 'Floor and wall covering'],
            ['code_id' => '43320', 'code_name' => 'Joinery installation'],
            ['code_id' => '43310', 'code_name' => 'Plastering'],
            ['code_id' => '43290', 'code_name' => 'Other construction installation'],
            ['code_id' => '43220', 'code_name' => 'Plumbing, heat and air-conditioning installation'],
            ['code_id' => '43210', 'code_name' => 'Electrical installation'],
            ['code_id' => '43130', 'code_name' => 'Test drilling and boring'],
            ['code_id' => '43120', 'code_name' => 'Site preparation'],
            ['code_id' => '43110', 'code_name' => 'Demolition'],
            ['code_id' => '42990', 'code_name' => 'Construction of other civil engineering projects n.e.c.'],
            ['code_id' => '42910', 'code_name' => 'Construction of water projects'],
            ['code_id' => '42220', 'code_name' => 'Construction of utility projects for electricity and telecommunications'],
            ['code_id' => '42210', 'code_name' => 'Construction of utility projects for fluids'],
            ['code_id' => '42130', 'code_name' => 'Construction of bridges and tunnels'],
            ['code_id' => '42120', 'code_name' => 'Construction of railways and underground railways'],
            ['code_id' => '42110', 'code_name' => 'Construction of roads and motorways'],
            ['code_id' => '41202', 'code_name' => 'Construction of domestic buildings'],
            ['code_id' => '41201', 'code_name' => 'Construction of commercial buildings'],
            ['code_id' => '41100', 'code_name' => 'Development of building projects'],
            ['code_id' => '85600', 'code_name' => 'Educational support services'],
            ['code_id' => '85590', 'code_name' => 'Other education n.e.c.'],
            ['code_id' => '85530', 'code_name' => 'Driving school activities'],
            ['code_id' => '85520', 'code_name' => 'Cultural education'],
            ['code_id' => '85510', 'code_name' => 'Sports and recreation education'],
            ['code_id' => '85422', 'code_name' => 'Post-graduate level higher education'],
            ['code_id' => '85421', 'code_name' => 'First-degree level higher education'],
            ['code_id' => '85410', 'code_name' => 'Post-secondary non-tertiary education'],
            ['code_id' => '85320', 'code_name' => 'Technical and vocational secondary education'],
            ['code_id' => '85310', 'code_name' => 'General secondary education'],
            ['code_id' => '85200', 'code_name' => 'Primary education'],
            ['code_id' => '85100', 'code_name' => 'Pre-primary education'],
            ['code_id' => '35300', 'code_name' => 'Steam and air conditioning supply'],
            ['code_id' => '35230', 'code_name' => 'Trade of gas through mains'],
            ['code_id' => '35220', 'code_name' => 'Distribution of gaseous fuels through mains'],
            ['code_id' => '35210', 'code_name' => 'Manufacture of gas'],
            ['code_id' => '35140', 'code_name' => 'Trade of electricity'],
            ['code_id' => '35130', 'code_name' => 'Distribution of electricity'],
            ['code_id' => '35120', 'code_name' => 'Transmission of electricity'],
            ['code_id' => '35110', 'code_name' => 'Production of electricity'],
            ['code_id' => '66300', 'code_name' => 'Fund management activities'],
            ['code_id' => '66290', 'code_name' => 'Other activities auxiliary to insurance and pension funding'],
            ['code_id' => '66220', 'code_name' => 'Activities of insurance agents and brokers'],
            ['code_id' => '66210', 'code_name' => 'Risk and damage evaluation'],
            ['code_id' => '66190', 'code_name' => 'Activities auxiliary to financial intermediation n.e.c.'],
            ['code_id' => '66120', 'code_name' => 'Security and commodity contracts dealing activities'],
            ['code_id' => '66110', 'code_name' => 'Administration of financial markets'],
            ['code_id' => '65300', 'code_name' => 'Pension funding'],
            ['code_id' => '65202', 'code_name' => 'Non-life reinsurance'],
            ['code_id' => '65201', 'code_name' => 'Life reinsurance'],
            ['code_id' => '65120', 'code_name' => 'Non-life insurance'],
            ['code_id' => '65110', 'code_name' => 'Life insurance'],
            ['code_id' => '64999', 'code_name' => 'Financial intermediation not elsewhere classified'],
            ['code_id' => '64992', 'code_name' => 'Factoring'],
            ['code_id' => '64991', 'code_name' => 'Security dealing on own account'],
            ['code_id' => '64929', 'code_name' => 'Other credit granting n.e.c.'],
            ['code_id' => '64922', 'code_name' => 'Activities of mortgage finance companies'],
            ['code_id' => '64921', 'code_name' => 'Credit granting by non-deposit taking finance houses and other specialist consumer credit grantors'],
            ['code_id' => '64910', 'code_name' => 'Financial leasing'],
            ['code_id' => '64306', 'code_name' => 'Activities of real estate investment trusts'],
            ['code_id' => '64305', 'code_name' => 'Activities of property unit trusts'],
            ['code_id' => '64304', 'code_name' => 'Activities of open-ended investment companies'],
            ['code_id' => '64303', 'code_name' => 'Activities of venture and development capital companies'],
            ['code_id' => '64302', 'code_name' => 'Activities of unit trusts'],
            ['code_id' => '64301', 'code_name' => 'Activities of investment trusts'],
            ['code_id' => '64209', 'code_name' => 'Activities of other holding companies n.e.c.'],
            ['code_id' => '64205', 'code_name' => 'Activities of financial services holding companies'],
            ['code_id' => '64204', 'code_name' => 'Activities of distribution holding companies'],
            ['code_id' => '64202', 'code_name' => 'Activities of production holding companies'],
            ['code_id' => '64201', 'code_name' => 'Activities of agricultural holding companies'],
            ['code_id' => '64192', 'code_name' => 'Building societies'],
            ['code_id' => '64191', 'code_name' => 'Banks'],
            ['code_id' => '64110', 'code_name' => 'Central banking'],
            ['code_id' => '88990', 'code_name' => 'Other social work activities without accommodation n.e.c.'],
            ['code_id' => '88910', 'code_name' => 'Child day-care activities'],
            ['code_id' => '88100', 'code_name' => 'Social work activities without accommodation for the elderly and disabled'],
            ['code_id' => '87900', 'code_name' => 'Other residential care activities n.e.c.'],
            ['code_id' => '87300', 'code_name' => 'Residential care activities for the elderly and disabled'],
            ['code_id' => '87200', 'code_name' => 'Residential care activities for learning difficulties, mental health and substance abuse'],
            ['code_id' => '87100', 'code_name' => 'Residential nursing care facilities'],
            ['code_id' => '86900', 'code_name' => 'Other human health activities'],
            ['code_id' => '86230', 'code_name' => 'Dental practice activities'],
            ['code_id' => '86220', 'code_name' => 'Specialists medical practice activities'],
            ['code_id' => '86210', 'code_name' => 'General medical practice activities'],
            ['code_id' => '86102', 'code_name' => 'Medical nursing home activities'],
            ['code_id' => '86101', 'code_name' => 'Hospital activities'],
            ['code_id' => '63990', 'code_name' => 'Other information service activities n.e.c.'],
            ['code_id' => '63910', 'code_name' => 'News agency activities'],
            ['code_id' => '63120', 'code_name' => 'Web portals'],
            ['code_id' => '63110', 'code_name' => 'Data processing, hosting and related activities'],
            ['code_id' => '62090', 'code_name' => 'Other information technology service activities'],
            ['code_id' => '62030', 'code_name' => 'Computer facilities management activities'],
            ['code_id' => '62020', 'code_name' => 'Information technology consultancy activities'],
            ['code_id' => '62012', 'code_name' => 'Business and domestic software development'],
            ['code_id' => '62011', 'code_name' => 'Ready-made interactive leisure and entertainment software development'],
            ['code_id' => '61900', 'code_name' => 'Other telecommunications activities'],
            ['code_id' => '61300', 'code_name' => 'Satellite telecommunications activities'],
            ['code_id' => '61200', 'code_name' => 'Wireless telecommunications activities'],
            ['code_id' => '61100', 'code_name' => 'Wired telecommunications activities'],
            ['code_id' => '60200', 'code_name' => 'Television programming and broadcasting activities'],
            ['code_id' => '60100', 'code_name' => 'Radio broadcasting'],
            ['code_id' => '59200', 'code_name' => 'Sound recording and music publishing activities'],
            ['code_id' => '59140', 'code_name' => 'Motion picture projection activities'],
            ['code_id' => '59133', 'code_name' => 'Television programme distribution activities'],
            ['code_id' => '59132', 'code_name' => 'Video distribution activities'],
            ['code_id' => '59131', 'code_name' => 'Motion picture distribution activities'],
            ['code_id' => '59120', 'code_name' => 'Motion picture, video and television programme post-production activities'],
            ['code_id' => '59113', 'code_name' => 'Television programme production activities'],
            ['code_id' => '59112', 'code_name' => 'Video production activities'],
            ['code_id' => '59111', 'code_name' => 'Motion picture production activities'],
            ['code_id' => '58290', 'code_name' => 'Other software publishing'],
            ['code_id' => '58210', 'code_name' => 'Publishing of computer games'],
            ['code_id' => '58190', 'code_name' => 'Other publishing activities'],
            ['code_id' => '58142', 'code_name' => 'Publishing of consumer and business journals and periodicals'],
            ['code_id' => '58141', 'code_name' => 'Publishing of learned journals'],
            ['code_id' => '58130', 'code_name' => 'Publishing of newspapers'],
            ['code_id' => '58120', 'code_name' => 'Publishing of directories and mailing lists'],
            ['code_id' => '58110', 'code_name' => 'Book publishing'],
            ['code_id' => '33200', 'code_name' => 'Installation of industrial machinery and equipment'],
            ['code_id' => '33190', 'code_name' => 'Repair of other equipment'],
            ['code_id' => '33170', 'code_name' => 'Repair and maintenance of other transport equipment n.e.c.'],
            ['code_id' => '33160', 'code_name' => 'Repair and maintenance of aircraft and spacecraft'],
            ['code_id' => '33150', 'code_name' => 'Repair and maintenance of ships and boats'],
            ['code_id' => '33140', 'code_name' => 'Repair of electrical equipment'],
            ['code_id' => '33130', 'code_name' => 'Repair of electronic and optical equipment'],
            ['code_id' => '33120', 'code_name' => 'Repair of machinery'],
            ['code_id' => '33110', 'code_name' => 'Repair of fabricated metal products'],
            ['code_id' => '32990', 'code_name' => 'Other manufacturing n.e.c.'],
            ['code_id' => '32910', 'code_name' => 'Manufacture of brooms and brushes'],
            ['code_id' => '32500', 'code_name' => 'Manufacture of medical and dental instruments and supplies'],
            ['code_id' => '32409', 'code_name' => 'Manufacture of other games and toys, n.e.c.'],
            ['code_id' => '32401', 'code_name' => 'Manufacture of professional and arcade games and toys'],
            ['code_id' => '32300', 'code_name' => 'Manufacture of sports goods'],
            ['code_id' => '32200', 'code_name' => 'Manufacture of musical instruments'],
            ['code_id' => '32130', 'code_name' => 'Manufacture of imitation jewellery and related articles'],
            ['code_id' => '32120', 'code_name' => 'Manufacture of jewellery and related articles'],
            ['code_id' => '32110', 'code_name' => 'Striking of coins'],
            ['code_id' => '31090', 'code_name' => 'Manufacture of other furniture'],
            ['code_id' => '31030', 'code_name' => 'Manufacture of mattresses'],
            ['code_id' => '31020', 'code_name' => 'Manufacture of kitchen furniture'],
            ['code_id' => '31010', 'code_name' => 'Manufacture of office and shop furniture'],
            ['code_id' => '30990', 'code_name' => 'Manufacture of other transport equipment n.e.c.'],
            ['code_id' => '30920', 'code_name' => 'Manufacture of bicycles and invalid carriages'],
            ['code_id' => '30910', 'code_name' => 'Manufacture of motorcycles'],
            ['code_id' => '30400', 'code_name' => 'Manufacture of military fighting vehicles'],
            ['code_id' => '30300', 'code_name' => 'Manufacture of air and spacecraft and related machinery'],
            ['code_id' => '30200', 'code_name' => 'Manufacture of railway locomotives and rolling stock'],
            ['code_id' => '30120', 'code_name' => 'Building of pleasure and sporting boats'],
            ['code_id' => '30110', 'code_name' => 'Building of ships and floating structures'],
            ['code_id' => '29320', 'code_name' => 'Manufacture of other parts and accessories for motor vehicles'],
            ['code_id' => '29310', 'code_name' => 'Manufacture of electrical and electronic equipment for motor vehicles and their engines'],
            ['code_id' => '29203', 'code_name' => 'Manufacture of caravans'],
            ['code_id' => '29202', 'code_name' => 'Manufacture of trailers and semi-trailers'],
            ['code_id' => '29201', 'code_name' => 'Manufacture of bodies (coachwork) for motor vehicles (except caravans)'],
            ['code_id' => '29100', 'code_name' => 'Manufacture of motor vehicles'],
            ['code_id' => '28990', 'code_name' => 'Manufacture of other special-purpose machinery n.e.c.'],
            ['code_id' => '28960', 'code_name' => 'Manufacture of plastics and rubber machinery'],
            ['code_id' => '28950', 'code_name' => 'Manufacture of machinery for paper and paperboard production'],
            ['code_id' => '28940', 'code_name' => 'Manufacture of machinery for textile, apparel and leather production'],
            ['code_id' => '28930', 'code_name' => 'Manufacture of machinery for food, beverage and tobacco processing'],
            ['code_id' => '28922', 'code_name' => 'Manufacture of earthmoving equipment'],
            ['code_id' => '28921', 'code_name' => 'Manufacture of machinery for mining'],
            ['code_id' => '28910', 'code_name' => 'Manufacture of machinery for metallurgy'],
            ['code_id' => '28490', 'code_name' => 'Manufacture of other machine tools'],
            ['code_id' => '28410', 'code_name' => 'Manufacture of metal forming machinery'],
            ['code_id' => '28302', 'code_name' => 'Manufacture of agricultural and forestry machinery other than tractors'],
            ['code_id' => '28301', 'code_name' => 'Manufacture of agricultural tractors'],
            ['code_id' => '28290', 'code_name' => 'Manufacture of other general-purpose machinery n.e.c.'],
            ['code_id' => '28250', 'code_name' => 'Manufacture of non-domestic cooling and ventilation equipment'],
            ['code_id' => '28240', 'code_name' => 'Manufacture of power-driven hand tools'],
            ['code_id' => '28230', 'code_name' => 'Manufacture of office machinery and equipment (except computers and peripheral equipment)'],
            ['code_id' => '28220', 'code_name' => 'Manufacture of lifting and handling equipment'],
            ['code_id' => '28210', 'code_name' => 'Manufacture of ovens, furnaces and furnace burners'],
            ['code_id' => '28150', 'code_name' => 'Manufacture of bearings, gears, gearing and driving elements'],
            ['code_id' => '28140', 'code_name' => 'Manufacture of taps and valves'],
            ['code_id' => '28132', 'code_name' => 'Manufacture of compressors'],
            ['code_id' => '28131', 'code_name' => 'Manufacture of pumps '],
            ['code_id' => '28120', 'code_name' => 'Manufacture of fluid power equipment'],
            ['code_id' => '28110', 'code_name' => 'Manufacture of engines and turbines, except aircraft, vehicle and cycle engines'],
            ['code_id' => '27900', 'code_name' => 'Manufacture of other electrical equipment'],
            ['code_id' => '27520', 'code_name' => 'Manufacture of non-electric domestic appliances'],
            ['code_id' => '27510', 'code_name' => 'Manufacture of electric domestic appliances'],
            ['code_id' => '27400', 'code_name' => 'Manufacture of electric lighting equipment'],
            ['code_id' => '27330', 'code_name' => 'Manufacture of wiring devices'],
            ['code_id' => '27320', 'code_name' => 'Manufacture of other electronic and electric wires and cables'],
            ['code_id' => '27310', 'code_name' => 'Manufacture of fibre optic cables'],
            ['code_id' => '27200', 'code_name' => 'Manufacture of batteries and accumulators'],
            ['code_id' => '27120', 'code_name' => 'Manufacture of electricity distribution and control apparatus'],
            ['code_id' => '27110', 'code_name' => 'Manufacture of electric motors, generators and transformers'],
            ['code_id' => '26800', 'code_name' => 'Manufacture of magnetic and optical media'],
            ['code_id' => '26702', 'code_name' => 'Manufacture of photographic and cinematographic equipment'],
            ['code_id' => '26701', 'code_name' => 'Manufacture of optical precision instruments'],
            ['code_id' => '26600', 'code_name' => 'Manufacture of irradiation, electromedical and electrotherapeutic equipment'],
            ['code_id' => '26520', 'code_name' => 'Manufacture of watches and clocks'],
            ['code_id' => '26514', 'code_name' => 'Manufacture of non-electronic industrial process control equipment'],
            ['code_id' => '26513', 'code_name' => 'Manufacture of non-electronic measuring, testing etc. equipment, not for industrial process control'],
            ['code_id' => '26512', 'code_name' => 'Manufacture of electronic industrial process control equipment'],
            ['code_id' => '26511', 'code_name' => 'Manufacture of electronic measuring, testing etc. equipment, not for industrial process control'],
            ['code_id' => '26400', 'code_name' => 'Manufacture of consumer electronics'],
            ['code_id' => '26309', 'code_name' => 'Manufacture of communication equipment other than telegraph, and telephone apparatus and equipment'],
            ['code_id' => '26301', 'code_name' => 'Manufacture of telegraph and telephone apparatus and equipment'],
            ['code_id' => '26200', 'code_name' => 'Manufacture of computers and peripheral equipment'],
            ['code_id' => '26120', 'code_name' => 'Manufacture of loaded electronic boards'],
            ['code_id' => '26110', 'code_name' => 'Manufacture of electronic components'],
            ['code_id' => '25990', 'code_name' => 'Manufacture of other fabricated metal products n.e.c.'],
            ['code_id' => '25940', 'code_name' => 'Manufacture of fasteners and screw machine products'],
            ['code_id' => '25930', 'code_name' => 'Manufacture of wire products, chain and springs'],
            ['code_id' => '25920', 'code_name' => 'Manufacture of light metal packaging'],
            ['code_id' => '25910', 'code_name' => 'Manufacture of steel drums and similar containers'],
            ['code_id' => '25730', 'code_name' => 'Manufacture of tools'],
            ['code_id' => '25720', 'code_name' => 'Manufacture of locks and hinges'],
            ['code_id' => '25710', 'code_name' => 'Manufacture of cutlery'],
            ['code_id' => '25620', 'code_name' => 'Machining'],
            ['code_id' => '25610', 'code_name' => 'Treatment and coating of metals'],
            ['code_id' => '25500', 'code_name' => 'Forging, pressing, stamping and roll-forming of metal; powder metallurgy'],
            ['code_id' => '25400', 'code_name' => 'Manufacture of weapons and ammunition'],
            ['code_id' => '25300', 'code_name' => 'Manufacture of steam generators, except central heating hot water boilers'],
            ['code_id' => '25290', 'code_name' => 'Manufacture of other tanks, reservoirs and containers of metal'],
            ['code_id' => '25210', 'code_name' => 'Manufacture of central heating radiators and boilers'],
            ['code_id' => '25120', 'code_name' => 'Manufacture of doors and windows of metal'],
            ['code_id' => '25110', 'code_name' => 'Manufacture of metal structures and parts of structures'],
            ['code_id' => '24540', 'code_name' => 'Casting of other non-ferrous metals'],
            ['code_id' => '24530', 'code_name' => 'Casting of light metals'],
            ['code_id' => '24520', 'code_name' => 'Casting of steel'],
            ['code_id' => '24510', 'code_name' => 'Casting of iron'],
            ['code_id' => '24460', 'code_name' => 'Processing of nuclear fuel'],
            ['code_id' => '24450', 'code_name' => 'Other non-ferrous metal production'],
            ['code_id' => '24440', 'code_name' => 'Copper production'],
            ['code_id' => '24430', 'code_name' => 'Lead, zinc and tin production'],
            ['code_id' => '24420', 'code_name' => 'Aluminium production'],
            ['code_id' => '24410', 'code_name' => 'Precious metals production'],
            ['code_id' => '24340', 'code_name' => 'Cold drawing of wire'],
            ['code_id' => '24330', 'code_name' => 'Cold forming or folding'],
            ['code_id' => '24320', 'code_name' => 'Cold rolling of narrow strip'],
            ['code_id' => '24310', 'code_name' => 'Cold drawing of bars'],
            ['code_id' => '24200', 'code_name' => 'Manufacture of tubes, pipes, hollow profiles and related fittings, of steel'],
            ['code_id' => '24100', 'code_name' => 'Manufacture of basic iron and steel and of ferro-alloys'],
            ['code_id' => '23990', 'code_name' => 'Manufacture of other non-metallic mineral products n.e.c.'],
            ['code_id' => '23910', 'code_name' => 'Production of abrasive products'],
            ['code_id' => '23700', 'code_name' => 'Cutting, shaping and finishing of stone'],
            ['code_id' => '23690', 'code_name' => 'Manufacture of other articles of concrete, plaster and cement'],
            ['code_id' => '23650', 'code_name' => 'Manufacture of fibre cement'],
            ['code_id' => '23640', 'code_name' => 'Manufacture of mortars'],
            ['code_id' => '23630', 'code_name' => 'Manufacture of ready-mixed concrete'],
            ['code_id' => '23620', 'code_name' => 'Manufacture of plaster products for construction purposes'],
            ['code_id' => '23610', 'code_name' => 'Manufacture of concrete products for construction purposes'],
            ['code_id' => '23520', 'code_name' => 'Manufacture of lime and plaster'],
            ['code_id' => '23510', 'code_name' => 'Manufacture of cement'],
            ['code_id' => '23490', 'code_name' => 'Manufacture of other ceramic products n.e.c.'],
            ['code_id' => '23440', 'code_name' => 'Manufacture of other technical ceramic products'],
            ['code_id' => '23430', 'code_name' => 'Manufacture of ceramic insulators and insulating fittings'],
            ['code_id' => '23420', 'code_name' => 'Manufacture of ceramic sanitary fixtures'],
            ['code_id' => '23410', 'code_name' => 'Manufacture of ceramic household and ornamental articles'],
            ['code_id' => '23320', 'code_name' => 'Manufacture of bricks, tiles and construction products, in baked clay'],
            ['code_id' => '23310', 'code_name' => 'Manufacture of ceramic tiles and flags'],
            ['code_id' => '23200', 'code_name' => 'Manufacture of refractory products'],
            ['code_id' => '23190', 'code_name' => 'Manufacture and processing of other glass, including technical glassware'],
            ['code_id' => '23140', 'code_name' => 'Manufacture of glass fibres'],
            ['code_id' => '23130', 'code_name' => 'Manufacture of hollow glass'],
            ['code_id' => '23120', 'code_name' => 'Shaping and processing of flat glass'],
            ['code_id' => '23110', 'code_name' => 'Manufacture of flat glass'],
            ['code_id' => '22290', 'code_name' => 'Manufacture of other plastic products'],
            ['code_id' => '22230', 'code_name' => 'Manufacture of builders ware of plastic'],
            ['code_id' => '22220', 'code_name' => 'Manufacture of plastic packing goods'],
            ['code_id' => '22210', 'code_name' => 'Manufacture of plastic plates, sheets, tubes and profiles'],
            ['code_id' => '22190', 'code_name' => 'Manufacture of other rubber products'],
            ['code_id' => '22110', 'code_name' => 'Manufacture of rubber tyres and tubes; retreading and rebuilding of rubber tyres'],
            ['code_id' => '21200', 'code_name' => 'Manufacture of pharmaceutical preparations'],
            ['code_id' => '21100', 'code_name' => 'Manufacture of basic pharmaceutical products'],
            ['code_id' => '20600', 'code_name' => 'Manufacture of man-made fibres'],
            ['code_id' => '20590', 'code_name' => 'Manufacture of other chemical products n.e.c.'],
            ['code_id' => '20530', 'code_name' => 'Manufacture of essential oils'],
            ['code_id' => '20520', 'code_name' => 'Manufacture of glues'],
            ['code_id' => '20510', 'code_name' => 'Manufacture of explosives'],
            ['code_id' => '20420', 'code_name' => 'Manufacture of perfumes and toilet preparations'],
            ['code_id' => '20412', 'code_name' => 'Manufacture of cleaning and polishing preparations'],
            ['code_id' => '20411', 'code_name' => 'Manufacture of soap and detergents'],
            ['code_id' => '20302', 'code_name' => 'Manufacture of printing ink'],
            ['code_id' => '20301', 'code_name' => 'Manufacture of paints, varnishes and similar coatings, mastics and sealants'],
            ['code_id' => '20200', 'code_name' => 'Manufacture of pesticides and other agrochemical products'],
            ['code_id' => '20170', 'code_name' => 'Manufacture of synthetic rubber in primary forms'],
            ['code_id' => '20160', 'code_name' => 'Manufacture of plastics in primary forms'],
            ['code_id' => '20150', 'code_name' => 'Manufacture of fertilizers and nitrogen compounds'],
            ['code_id' => '20140', 'code_name' => 'Manufacture of other organic basic chemicals'],
            ['code_id' => '20130', 'code_name' => 'Manufacture of other inorganic basic chemicals'],
            ['code_id' => '20120', 'code_name' => 'Manufacture of dyes and pigments'],
            ['code_id' => '20110', 'code_name' => 'Manufacture of industrial gases'],
            ['code_id' => '19209', 'code_name' => 'Other treatment of petroleum products (excluding petrochemicals manufacture)'],
            ['code_id' => '19201', 'code_name' => 'Mineral oil refining'],
            ['code_id' => '19100', 'code_name' => 'Manufacture of coke oven products'],
            ['code_id' => '18203', 'code_name' => 'Reproduction of computer media'],
            ['code_id' => '18202', 'code_name' => 'Reproduction of video recording'],
            ['code_id' => '18201', 'code_name' => 'Reproduction of sound recording'],
            ['code_id' => '18140', 'code_name' => 'Binding and related services'],
            ['code_id' => '18130', 'code_name' => 'Pre-press and pre-media services'],
            ['code_id' => '18129', 'code_name' => 'Printing n.e.c.'],
            ['code_id' => '18121', 'code_name' => 'Manufacture of printed labels'],
            ['code_id' => '18110', 'code_name' => 'Printing of newspapers'],
            ['code_id' => '17290', 'code_name' => 'Manufacture of other articles of paper and paperboard n.e.c.'],
            ['code_id' => '17240', 'code_name' => 'Manufacture of wallpaper'],
            ['code_id' => '17230', 'code_name' => 'Manufacture of paper stationery'],
            ['code_id' => '17220', 'code_name' => 'Manufacture of household and sanitary goods and of toilet requisites'],
            ['code_id' => '17219', 'code_name' => 'Manufacture of other paper and paperboard containers'],
            ['code_id' => '17211', 'code_name' => 'Manufacture of corrugated paper and paperboard, sacks and bags'],
            ['code_id' => '17120', 'code_name' => 'Manufacture of paper and paperboard'],
            ['code_id' => '17110', 'code_name' => 'Manufacture of pulp'],
            ['code_id' => '16290', 'code_name' => 'Manufacture of other products of wood; manufacture of articles of cork, straw and plaiting materials'],
            ['code_id' => '16240', 'code_name' => 'Manufacture of wooden containers'],
            ['code_id' => '16230', 'code_name' => "Manufacture of other builders' carpentry and joinery"],
            ['code_id' => '16220', 'code_name' => 'Manufacture of assembled parquet floors'],
            ['code_id' => '16210', 'code_name' => 'Manufacture of veneer sheets and wood-based panels'],
            ['code_id' => '16100', 'code_name' => 'Sawmilling and planing of wood'],
            ['code_id' => '15200', 'code_name' => 'Manufacture of footwear'],
            ['code_id' => '15120', 'code_name' => 'Manufacture of luggage, handbags and the like, saddlery and harness'],
            ['code_id' => '15110', 'code_name' => 'Tanning and dressing of leather; dressing and dyeing of fur'],
            ['code_id' => '14390', 'code_name' => 'Manufacture of other knitted and crocheted apparel'],
            ['code_id' => '14310', 'code_name' => 'Manufacture of knitted and crocheted hosiery'],
            ['code_id' => '14200', 'code_name' => 'Manufacture of articles of fur'],
            ['code_id' => '14190', 'code_name' => 'Manufacture of other wearing apparel and accessories n.e.c.'],
            ['code_id' => '14142', 'code_name' => "Manufacture of women's underwear"],
            ['code_id' => '14141', 'code_name' => "Manufacture of men's underwear"],
            ['code_id' => '14132', 'code_name' => "Manufacture of other women's outerwear"],
            ['code_id' => '14131', 'code_name' => "Manufacture of other men's outerwear"],
            ['code_id' => '14120', 'code_name' => 'Manufacture of workwear'],
            ['code_id' => '14110', 'code_name' => 'Manufacture of leather clothes'],
            ['code_id' => '13990', 'code_name' => 'Manufacture of other textiles n.e.c.'],
            ['code_id' => '13960', 'code_name' => 'Manufacture of other technical and industrial textiles'],
            ['code_id' => '13950', 'code_name' => 'Manufacture of non-wovens and articles made from non-wovens, except apparel'],
            ['code_id' => '13940', 'code_name' => 'Manufacture of cordage, rope, twine and netting'],
            ['code_id' => '13939', 'code_name' => 'Manufacture of other carpets and rugs'],
            ['code_id' => '13931', 'code_name' => 'Manufacture of woven or tufted carpets and rugs'],
            ['code_id' => '13923', 'code_name' => 'Manufacture of household textiles'],
            ['code_id' => '13922', 'code_name' => 'Manufacture of canvas goods, sacks, etc.'],
            ['code_id' => '13921', 'code_name' => 'Manufacture of soft furnishings'],
            ['code_id' => '13910', 'code_name' => 'Manufacture of knitted and crocheted fabrics'],
            ['code_id' => '13300', 'code_name' => 'Finishing of textiles'],
            ['code_id' => '13200', 'code_name' => 'Weaving of textiles'],
            ['code_id' => '13100', 'code_name' => 'Preparation and spinning of textile fibres'],
            ['code_id' => '12000', 'code_name' => 'Manufacture of tobacco products'],
            ['code_id' => '11070', 'code_name' => 'Manufacture of soft drinks; production of mineral waters and other bottled waters'],
            ['code_id' => '11060', 'code_name' => 'Manufacture of malt'],
            ['code_id' => '11050', 'code_name' => 'Manufacture of beer'],
            ['code_id' => '11040', 'code_name' => 'Manufacture of other non-distilled fermented beverages'],
            ['code_id' => '11030', 'code_name' => 'Manufacture of cider and other fruit wines'],
            ['code_id' => '11020', 'code_name' => 'Manufacture of wine from grape'],
            ['code_id' => '11010', 'code_name' => 'Distilling, rectifying and blending of spirits'],
            ['code_id' => '10920', 'code_name' => 'Manufacture of prepared pet foods'],
            ['code_id' => '10910', 'code_name' => 'Manufacture of prepared feeds for farm animals'],
            ['code_id' => '10890', 'code_name' => 'Manufacture of other food products n.e.c.'],
            ['code_id' => '10860', 'code_name' => 'Manufacture of homogenized food preparations and dietetic food'],
            ['code_id' => '10850', 'code_name' => 'Manufacture of prepared meals and dishes'],
            ['code_id' => '10840', 'code_name' => 'Manufacture of condiments and seasonings'],
            ['code_id' => '10832', 'code_name' => 'Production of coffee and coffee substitutes'],
            ['code_id' => '10831', 'code_name' => 'Tea processing'],
            ['code_id' => '10822', 'code_name' => 'Manufacture of sugar confectionery'],
            ['code_id' => '10821', 'code_name' => 'Manufacture of cocoa and chocolate confectionery'],
            ['code_id' => '10810', 'code_name' => 'Manufacture of sugar'],
            ['code_id' => '10730', 'code_name' => 'Manufacture of macaroni, noodles, couscous and similar farinaceous products'],
            ['code_id' => '10720', 'code_name' => 'Manufacture of rusks and biscuits; manufacture of preserved pastry goods and cakes'],
            ['code_id' => '10710', 'code_name' => 'Manufacture of bread; manufacture of fresh pastry goods and cakes'],
            ['code_id' => '10620', 'code_name' => 'Manufacture of starches and starch products'],
            ['code_id' => '10612', 'code_name' => 'Manufacture of breakfast cereals and cereals-based food'],
            ['code_id' => '10611', 'code_name' => 'Grain milling'],
            ['code_id' => '10520', 'code_name' => 'Manufacture of ice cream'],
            ['code_id' => '10519', 'code_name' => 'Manufacture of other milk products'],
            ['code_id' => '10512', 'code_name' => 'Butter and cheese production'],
            ['code_id' => '10511', 'code_name' => 'Liquid milk and cream production'],
            ['code_id' => '10420', 'code_name' => 'Manufacture of margarine and similar edible fats'],
            ['code_id' => '10410', 'code_name' => 'Manufacture of oils and fats'],
            ['code_id' => 'Other processing and preserving of fruit and vegetables', 'code_name' => 'Other processing and preserving of fruit and vegetables'],
            ['code_id' => '10320', 'code_name' => 'Manufacture of fruit and vegetable juice'],
            ['code_id' => '10310', 'code_name' => 'Processing and preserving of potatoes'],
            ['code_id' => '10200', 'code_name' => 'Processing and preserving of fish, crustaceans and molluscs'],
            ['code_id' => '10130', 'code_name' => 'Production of meat and poultry meat products'],
            ['code_id' => '10120', 'code_name' => 'Processing and preserving of poultry meat'],
            ['code_id' => '10110', 'code_name' => 'Processing and preserving of meat'],
            ['code_id' => '09900', 'code_name' => 'Support activities for other mining and quarrying'],
            ['code_id' => '09100', 'code_name' => 'Support activities for petroleum and natural gas mining'],
            ['code_id' => '08990', 'code_name' => 'Other mining and quarrying n.e.c.'],
            ['code_id' => '08930', 'code_name' => 'Extraction of salt'],
            ['code_id' => '08920', 'code_name' => 'Extraction of peat'],
            ['code_id' => '08910', 'code_name' => 'Mining of chemical and fertilizer minerals'],
            ['code_id' => '08120', 'code_name' => 'Operation of gravel and sand pits; mining of clays and kaolin'],
            ['code_id' => '08110', 'code_name' => 'Quarrying of ornamental and building stone, limestone, gypsum, chalk and slate'],
            ['code_id' => '07290', 'code_name' => 'Mining of other non-ferrous metal ores'],
            ['code_id' => '07210', 'code_name' => 'Mining of uranium and thorium ores'],
            ['code_id' => '07100', 'code_name' => 'Mining of iron ores'],
            ['code_id' => '06200', 'code_name' => 'Extraction of natural gas'],
            ['code_id' => '06100', 'code_name' => 'Extraction of crude petroleum'],
            ['code_id' => '05200', 'code_name' => 'Mining of lignite'],
            ['code_id' => '05102', 'code_name' => 'Open cast coal working'],
            ['code_id' => '05101', 'code_name' => 'Deep coal mines'],
            ['code_id' => '96090', 'code_name' => 'Other service activities n.e.c.'],
            ['code_id' => '96040', 'code_name' => 'Physical well-being activities'],
            ['code_id' => '96030', 'code_name' => 'Funeral and related activities'],
            ['code_id' => '96020', 'code_name' => 'Hairdressing and other beauty treatment'],
            ['code_id' => '96010', 'code_name' => 'Washing and (dry-)cleaning of textile and fur products'],
            ['code_id' => '95290', 'code_name' => 'Repair of personal and household goods n.e.c.'],
            ['code_id' => '95250', 'code_name' => 'Repair of watches, clocks and jewellery'],
            ['code_id' => '95240', 'code_name' => 'Repair of furniture and home furnishings'],
            ['code_id' => '95230', 'code_name' => 'Repair of footwear and leather goods'],
            ['code_id' => '95220', 'code_name' => 'Repair of household appliances and home and garden equipment'],
            ['code_id' => '95210', 'code_name' => 'Repair of consumer electronics'],
            ['code_id' => '95120', 'code_name' => 'Repair of communication equipment'],
            ['code_id' => '95110', 'code_name' => 'Repair of computers and peripheral equipment'],
            ['code_id' => '94990', 'code_name' => 'Activities of other membership organisations n.e.c.'],
            ['code_id' => '94920', 'code_name' => 'Activities of political organisations'],
            ['code_id' => '94910', 'code_name' => 'Activities of religious organisations'],
            ['code_id' => '94200', 'code_name' => 'Activities of trade unions'],
            ['code_id' => '94120', 'code_name' => 'Activities of professional membership organisations'],
            ['code_id' => '94110', 'code_name' => 'Activities of business and employers membership organisations'],
            ['code_id' => '75000', 'code_name' => 'Veterinary activities'],
            ['code_id' => '74990', 'code_name' => 'Non-trading company'],
            ['code_id' => '74909', 'code_name' => 'Other professional, scientific and technical activities n.e.c.'],
            ['code_id' => '74902', 'code_name' => 'Quantity surveying activities'],
            ['code_id' => '74901', 'code_name' => 'Environmental consulting activities'],
            ['code_id' => '74300', 'code_name' => 'Translation and interpretation activities'],
            ['code_id' => '74209', 'code_name' => 'Photographic activities not elsewhere classified'],
            ['code_id' => '74203', 'code_name' => 'Film processing'],
            ['code_id' => '74202', 'code_name' => 'Other specialist photography'],
            ['code_id' => '74201', 'code_name' => 'Portrait photographic activities'],
            ['code_id' => '74100', 'code_name' => 'specialised design activities'],
            ['code_id' => '73200', 'code_name' => 'Market research and public opinion polling'],
            ['code_id' => '73120', 'code_name' => 'Media representation services'],
            ['code_id' => '73110', 'code_name' => 'Advertising agencies'],
            ['code_id' => '72200', 'code_name' => 'Research and experimental development on social sciences and humanities'],
            ['code_id' => '72190', 'code_name' => 'Other research and experimental development on natural sciences and engineering'],
            ['code_id' => '72110', 'code_name' => 'Research and experimental development on biotechnology'],
            ['code_id' => '71200', 'code_name' => 'Technical testing and analysis'],
            ['code_id' => '71129', 'code_name' => 'Other engineering activities'],
            ['code_id' => '71122', 'code_name' => 'Engineering related scientific and technical consulting activities'],
            ['code_id' => '71121', 'code_name' => 'Engineering design activities for industrial process and production'],
            ['code_id' => '71112', 'code_name' => 'Urban planning and landscape architectural activities'],
            ['code_id' => '71111', 'code_name' => 'Architectural activities'],
            ['code_id' => '70229', 'code_name' => 'Management consultancy activities other than financial management'],
            ['code_id' => '70221', 'code_name' => 'Financial management'],
            ['code_id' => '70210', 'code_name' => 'Public relations and communications activities'],
            ['code_id' => '70100', 'code_name' => 'Activities of head offices'],
            ['code_id' => '69203', 'code_name' => 'Tax consultancy'],
            ['code_id' => '69202', 'code_name' => 'Bookkeeping activities'],
            ['code_id' => '69201', 'code_name' => 'Accounting and auditing activities'],
            ['code_id' => '69109', 'code_name' => 'Activities of patent and copyright agents; other legal activities n.e.c.'],
            ['code_id' => '69102', 'code_name' => 'Solicitors'],
            ['code_id' => '69101', 'code_name' => 'Barristers at law'],
            ['code_id' => '84300', 'code_name' => 'Compulsory social security activities'],
            ['code_id' => '84250', 'code_name' => 'Fire service activities'],
            ['code_id' => '84240', 'code_name' => 'Public order and safety activities'],
            ['code_id' => '84230', 'code_name' => 'Justice and judicial activities'],
            ['code_id' => '84220', 'code_name' => 'Defence activities'],
            ['code_id' => '84210', 'code_name' => 'Foreign affairs'],
            ['code_id' => '84130', 'code_name' => 'Regulation of and contribution to more efficient operation of businesses'],
            ['code_id' => '84120', 'code_name' => 'Regulation of health care, education, cultural and other social services'],
            ['code_id' => '84110', 'code_name' => 'General public administration activities'],
            ['code_id' => '68320', 'code_name' => 'Management of real estate on a fee or contract basis'],
            ['code_id' => '68310', 'code_name' => 'Real estate agencies'],
            ['code_id' => '68209', 'code_name' => 'Other letting and operating of own or leased real estate'],
            ['code_id' => '68202', 'code_name' => 'Letting and operating of conference and exhibition centres'],
            ['code_id' => '68201', 'code_name' => 'Renting and operating of Housing Association real estate'],
            ['code_id' => '68100', 'code_name' => 'Buying and selling of own real estate'],
            ['code_id' => '53202', 'code_name' => 'Unlicensed carriers'],
            ['code_id' => '53201', 'code_name' => 'Licensed carriers'],
            ['code_id' => '53100', 'code_name' => 'Postal activities under universal service obligation'],
            ['code_id' => '52290', 'code_name' => 'Other transportation support activities'],
            ['code_id' => '52243', 'code_name' => 'Cargo handling for land transport activities'],
            ['code_id' => '52242', 'code_name' => 'Cargo handling for air transport activities'],
            ['code_id' => '52241', 'code_name' => 'Cargo handling for water transport activities'],
            ['code_id' => '52230', 'code_name' => 'Service activities incidental to air transportation'],
            ['code_id' => '52220', 'code_name' => 'Service activities incidental to water transportation'],
            ['code_id' => '52219', 'code_name' => 'Other service activities incidental to land transportation, n.e.c.'],
            ['code_id' => '52213', 'code_name' => 'Operation of bus and coach passenger facilities at bus and coach stations'],
            ['code_id' => '52212', 'code_name' => 'Operation of rail passenger facilities at railway stations'],
            ['code_id' => '52211', 'code_name' => 'Operation of rail freight terminals'],
            ['code_id' => '52103', 'code_name' => 'Operation of warehousing and storage facilities for land transport activities'],
            ['code_id' => '52102', 'code_name' => 'Operation of warehousing and storage facilities for air transport activities'],
            ['code_id' => '52101', 'code_name' => 'Operation of warehousing and storage facilities for water transport activities'],
            ['code_id' => '51220', 'code_name' => 'Space transport'],
            ['code_id' => '51210', 'code_name' => 'Freight air transport'],
            ['code_id' => '51102', 'code_name' => 'Non-scheduled passenger air transport'],
            ['code_id' => '51101', 'code_name' => 'Scheduled passenger air transport'],
            ['code_id' => '50400', 'code_name' => 'Inland freight water transport'],
            ['code_id' => '50300', 'code_name' => 'Inland passenger water transport'],
            ['code_id' => '50200', 'code_name' => 'Sea and coastal freight water transport'],
            ['code_id' => '50100', 'code_name' => 'Sea and coastal passenger water transport'],
            ['code_id' => '49500', 'code_name' => 'Transport via pipeline'],
            ['code_id' => '49420', 'code_name' => 'Removal services'],
            ['code_id' => '49410', 'code_name' => 'Freight transport by road'],
            ['code_id' => '49390', 'code_name' => 'Other passenger land transport'],
            ['code_id' => '49320', 'code_name' => 'Taxi operation'],
            ['code_id' => '49319', 'code_name' => 'Other urban, suburban or metropolitan passenger land transport (not underground, metro or similar)'],
            ['code_id' => '49311', 'code_name' => 'Urban and suburban passenger railway transportation by underground, metro and similar systems'],
            ['code_id' => '49200', 'code_name' => 'Freight rail transport'],
            ['code_id' => '49100', 'code_name' => 'Passenger rail transport, interurban'],
            ['code_id' => '39000', 'code_name' => 'Remediation activities and other waste management services'],
            ['code_id' => '38320', 'code_name' => 'Recovery of sorted materials'],
            ['code_id' => '38310', 'code_name' => 'Dismantling of wrecks'],
            ['code_id' => '38220', 'code_name' => 'Treatment and disposal of hazardous waste'],
            ['code_id' => '38210', 'code_name' => 'Treatment and disposal of non-hazardous waste'],
            ['code_id' => '38120', 'code_name' => 'Collection of hazardous waste'],
            ['code_id' => '38110', 'code_name' => 'Collection of non-hazardous waste'],
            ['code_id' => '37000', 'code_name' => 'Sewerage'],
            ['code_id' => '36000', 'code_name' => 'Water collection, treatment and supply'],
            ['code_id' => '47990', 'code_name' => 'Other retail sale not in stores, stalls or markets'],
            ['code_id' => '47910', 'code_name' => 'Retail sale via mail order houses or via Internet'],
            ['code_id' => '47890', 'code_name' => 'Retail sale via stalls and markets of other goods'],
            ['code_id' => '47820', 'code_name' => 'Retail sale via stalls and markets of textiles, clothing and footwear'],
            ['code_id' => '47810', 'code_name' => 'Retail sale via stalls and markets of food, beverages and tobacco products'],
            ['code_id' => '47799', 'code_name' => 'Retail sale of other second-hand goods in stores (not incl. antiques)'],
            ['code_id' => '47791', 'code_name' => 'Retail sale of antiques including antique books in stores'],
            ['code_id' => '47789', 'code_name' => 'Other retail sale of new goods in specialised stores (not commercial art galleries and opticians)'],
            ['code_id' => '47782', 'code_name' => 'Retail sale by opticians'],
            ['code_id' => '47781', 'code_name' => 'Retail sale in commercial art galleries'],
            ['code_id' => '47770', 'code_name' => 'Retail sale of watches and jewellery in specialised stores'],
            ['code_id' => '47760', 'code_name' => 'Retail sale of flowers, plants, seeds, fertilizers, pet animals and pet food in specialised stores'],
            ['code_id' => '47750', 'code_name' => 'Retail sale of cosmetic and toilet articles in specialised stores'],
            ['code_id' => '47749', 'code_name' => 'Retail sale of medical and orthopaedic goods in specialised stores (not incl. hearing aids) n.e.c.'],
            ['code_id' => '47741', 'code_name' => 'Retail sale of hearing aids'],
            ['code_id' => '47730', 'code_name' => 'Dispensing chemist in specialised stores'],
            ['code_id' => '47722', 'code_name' => 'Retail sale of leather goods in specialised stores'],
            ['code_id' => '47721', 'code_name' => 'Retail sale of footwear in specialised stores'],
            ['code_id' => '47710', 'code_name' => 'Retail sale of clothing in specialised stores'],
            ['code_id' => '47650', 'code_name' => 'Retail sale of games and toys in specialised stores'],
            ['code_id' => '47640', 'code_name' => 'Retail sale of sports goods, fishing gear, camping goods, boats and bicycles'],
            ['code_id' => '47630', 'code_name' => 'Retail sale of music and video recordings in specialised stores'],
            ['code_id' => '47620', 'code_name' => 'Retail sale of newspapers and stationery in specialised stores'],
            ['code_id' => '47610', 'code_name' => 'Retail sale of books in specialised stores'],
            ['code_id' => '47599', 'code_name' => 'Retail of furniture, lighting, and similar (not musical instruments or scores) in specialised store'],
            ['code_id' => '47591', 'code_name' => 'Retail sale of musical instruments and scores'],
            ['code_id' => '47540', 'code_name' => 'Retail sale of electrical household appliances in specialised stores'],
            ['code_id' => '47530', 'code_name' => 'Retail sale of carpets, rugs, wall and floor coverings in specialised stores'],
            ['code_id' => '47520', 'code_name' => 'Retail sale of hardware, paints and glass in specialised stores'],
            ['code_id' => '47510', 'code_name' => 'Retail sale of textiles in specialised stores'],
            ['code_id' => '47430', 'code_name' => 'Retail sale of audio and video equipment in specialised stores'],
            ['code_id' => '47429', 'code_name' => 'Retail sale of telecommunications equipment other than mobile telephones'],
            ['code_id' => '47421', 'code_name' => 'Retail sale of mobile telephones'],
            ['code_id' => '47410', 'code_name' => 'Retail sale of computers, peripheral units and software in specialised stores'],
            ['code_id' => '47300', 'code_name' => 'Retail sale of automotive fuel in specialised stores'],
            ['code_id' => '47290', 'code_name' => 'Other retail sale of food in specialised stores'],
            ['code_id' => '47260', 'code_name' => 'Retail sale of tobacco products in specialised stores'],
            ['code_id' => '47250', 'code_name' => 'Retail sale of beverages in specialised stores'],
            ['code_id' => '47240', 'code_name' => 'Retail sale of bread, cakes, flour confectionery and sugar confectionery in specialised stores'],
            ['code_id' => '47230', 'code_name' => 'Retail sale of fish, crustaceans and molluscs in specialised stores'],
            ['code_id' => '47220', 'code_name' => 'Retail sale of meat and meat products in specialised stores'],
            ['code_id' => '47210', 'code_name' => 'Retail sale of fruit and vegetables in specialised stores'],
            ['code_id' => '47190', 'code_name' => 'Other retail sale in non-specialised stores'],
            ['code_id' => '47110', 'code_name' => 'Retail sale in non-specialised stores with food, beverages or tobacco predominating'],
            ['code_id' => '46900', 'code_name' => 'Non-specialised wholesale trade'],
            ['code_id' => '46770', 'code_name' => 'Wholesale of waste and scrap'],
            ['code_id' => '46760', 'code_name' => 'Wholesale of other intermediate products'],
            ['code_id' => '46750', 'code_name' => 'Wholesale of chemical products'],
            ['code_id' => '46740', 'code_name' => 'Wholesale of hardware, plumbing and heating equipment and supplies'],
            ['code_id' => '46730', 'code_name' => 'Wholesale of wood, construction materials and sanitary equipment'],
            ['code_id' => '46720', 'code_name' => 'Wholesale of metals and metal ores'],
            ['code_id' => '46719', 'code_name' => 'Wholesale of other fuels and related products'],
            ['code_id' => '46711', 'code_name' => 'Wholesale of petroleum and petroleum products'],
            ['code_id' => '46690', 'code_name' => 'Wholesale of other machinery and equipment'],
            ['code_id' => '46660', 'code_name' => 'Wholesale of other office machinery and equipment'],
            ['code_id' => '46650', 'code_name' => 'Wholesale of office furniture'],
            ['code_id' => '46640', 'code_name' => 'Wholesale of machinery for the textile industry and of sewing and knitting machines'],
            ['code_id' => '46630', 'code_name' => 'Wholesale of mining, construction and civil engineering machinery'],
            ['code_id' => '46620', 'code_name' => 'Wholesale of machine tools'],
            ['code_id' => '46610', 'code_name' => 'Wholesale of agricultural machinery, equipment and supplies'],
            ['code_id' => '46520', 'code_name' => 'Wholesale of electronic and telecommunications equipment and parts'],
            ['code_id' => '46510', 'code_name' => 'Wholesale of computers, computer peripheral equipment and software'],
            ['code_id' => '46499', 'code_name' => 'Wholesale of household goods (other than musical instruments) n.e.c'],
            ['code_id' => '46491', 'code_name' => 'Wholesale of musical instruments'],
            ['code_id' => '46480', 'code_name' => 'Wholesale of watches and jewellery'],
            ['code_id' => '46470', 'code_name' => 'Wholesale of furniture, carpets and lighting equipment'],
            ['code_id' => '46460', 'code_name' => 'Wholesale of pharmaceutical goods'],
            ['code_id' => '46450', 'code_name' => 'Wholesale of perfume and cosmetics'],
            ['code_id' => '46440', 'code_name' => 'Wholesale of china and glassware and cleaning materials'],
            ['code_id' => '46439', 'code_name' => "Wholesale of radio, television goods &amp; electrical household appliances (other than records, tapes, CD's &amp; video tapes and the equipment used for playing them)"],
            ['code_id' => '46431', 'code_name' => 'Wholesale of audio tapes, records, CDs and video tapes and the equipment on which these are played'],
            ['code_id' => '46420', 'code_name' => 'Wholesale of clothing and footwear'],
            ['code_id' => '46410', 'code_name' => 'Wholesale of textiles'],
            ['code_id' => '46390', 'code_name' => 'Non-specialised wholesale of food, beverages and tobacco'],
            ['code_id' => '46380', 'code_name' => 'Wholesale of other food, including fish, crustaceans and molluscs'],
            ['code_id' => '46370', 'code_name' => 'Wholesale of coffee, tea, cocoa and spices'],
            ['code_id' => '46360', 'code_name' => 'Wholesale of sugar and chocolate and sugar confectionery'],
            ['code_id' => '46350', 'code_name' => 'Wholesale of tobacco products'],
            ['code_id' => '46342', 'code_name' => 'Wholesale of wine, beer, spirits and other alcoholic beverages'],
            ['code_id' => '46341', 'code_name' => 'Wholesale of fruit and vegetable juices, mineral water and soft drinks'],
            ['code_id' => '46330', 'code_name' => 'Wholesale of dairy products, eggs and edible oils and fats'],
            ['code_id' => '46320', 'code_name' => 'Wholesale of meat and meat products'],
            ['code_id' => '46310', 'code_name' => 'Wholesale of fruit and vegetables'],
            ['code_id' => '46240', 'code_name' => 'Wholesale of hides, skins and leather'],
            ['code_id' => '46230', 'code_name' => 'Wholesale of live animals'],
            ['code_id' => '46220', 'code_name' => 'Wholesale of flowers and plants'],
            ['code_id' => '46210', 'code_name' => 'Wholesale of grain, unmanufactured tobacco, seeds and animal feeds'],
            ['code_id' => '46190', 'code_name' => 'Agents involved in the sale of a variety of goods'],
            ['code_id' => '46180', 'code_name' => 'Agents specialised in the sale of other particular products'],
            ['code_id' => '46170', 'code_name' => 'Agents involved in the sale of food, beverages and tobacco'],
            ['code_id' => '46160', 'code_name' => 'Agents involved in the sale of textiles, clothing, fur, footwear and leather goods'],
            ['code_id' => '46150', 'code_name' => 'Agents involved in the sale of furniture, household goods, hardware and ironmongery'],
            ['code_id' => '46140', 'code_name' => 'Agents involved in the sale of machinery, industrial equipment, ships and aircraft'],
            ['code_id' => '46130', 'code_name' => 'Agents involved in the sale of timber and building materials'],
            ['code_id' => '46120', 'code_name' => 'Agents involved in the sale of fuels, ores, metals and industrial chemicals'],
            ['code_id' => '46110', 'code_name' => 'Agents selling agricultural raw materials, livestock, textile raw materials and semi-finished goods'],
            ['code_id' => '45400', 'code_name' => 'Sale, maintenance and repair of motorcycles and related parts and accessories'],
            ['code_id' => '45320', 'code_name' => 'Retail trade of motor vehicle parts and accessories'],
            ['code_id' => '45310', 'code_name' => 'Wholesale trade of motor vehicle parts and accessories'],
            ['code_id' => '45200', 'code_name' => 'Maintenance and repair of motor vehicles'],
            ['code_id' => '45190', 'code_name' => 'Sale of other motor vehicles'],
            ['code_id' => '45112', 'code_name' => 'Sale of used cars and light motor vehicles'],
            ['code_id' => '45111', 'code_name' => 'Sale of new cars and light motor vehicles'],



            // Add more rows as needed...
        ];

        SicDetails::insert($data);
    }
}
